/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentAttr } from './authUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode } from './authUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode';

export interface AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponent {
  attr: AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `invalid_token` - invalid_token
* `invalid_uid` - invalid_uid */
  code: AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
