/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMePartialUpdateNonFieldErrorsErrorComponentAttr } from './authUsersMePartialUpdateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersMePartialUpdateNonFieldErrorsErrorComponentCode } from './authUsersMePartialUpdateNonFieldErrorsErrorComponentCode';

export interface AuthUsersMePartialUpdateNonFieldErrorsErrorComponent {
  attr: AuthUsersMePartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: AuthUsersMePartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
