/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersUpdateNonFieldErrorsErrorComponentAttr } from './authUsersUpdateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersUpdateNonFieldErrorsErrorComponentCode } from './authUsersUpdateNonFieldErrorsErrorComponentCode';

export interface AuthUsersUpdateNonFieldErrorsErrorComponent {
  attr: AuthUsersUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: AuthUsersUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
