/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `email_not_found` - email_not_found
* `invalid` - invalid
 */
export type AuthUsersResendActivationCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersResendActivationCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersResendActivationCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResendActivationCreateNonFieldErrorsErrorComponentCode = {
  email_not_found: 'email_not_found',
  invalid: 'invalid',
} as const;
