/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetPasswordCreateNonFieldErrorsErrorComponent } from './authUsersResetPasswordCreateNonFieldErrorsErrorComponent';
import type { AuthUsersResetPasswordCreateEmailErrorComponent } from './authUsersResetPasswordCreateEmailErrorComponent';

export type AuthUsersResetPasswordCreateError = AuthUsersResetPasswordCreateNonFieldErrorsErrorComponent | AuthUsersResetPasswordCreateEmailErrorComponent;
