/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenLoginCreateNonFieldErrorsErrorComponent } from './authTokenLoginCreateNonFieldErrorsErrorComponent';
import type { AuthTokenLoginCreatePasswordErrorComponent } from './authTokenLoginCreatePasswordErrorComponent';
import type { AuthTokenLoginCreateUsernameErrorComponent } from './authTokenLoginCreateUsernameErrorComponent';

export type AuthTokenLoginCreateError = AuthTokenLoginCreateNonFieldErrorsErrorComponent | AuthTokenLoginCreatePasswordErrorComponent | AuthTokenLoginCreateUsernameErrorComponent;
