/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
* `invalid_password` - invalid_password
 */
export type AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  invalid_password: 'invalid_password',
} as const;
