/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResendActivationCreateEmailErrorComponentAttr } from './authUsersResendActivationCreateEmailErrorComponentAttr';
import type { AuthUsersResendActivationCreateEmailErrorComponentCode } from './authUsersResendActivationCreateEmailErrorComponentCode';

export interface AuthUsersResendActivationCreateEmailErrorComponent {
  attr: AuthUsersResendActivationCreateEmailErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersResendActivationCreateEmailErrorComponentCode;
  detail: string;
}
