/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersUpdateNonFieldErrorsErrorComponentAttr = typeof AuthUsersUpdateNonFieldErrorsErrorComponentAttr[keyof typeof AuthUsersUpdateNonFieldErrorsErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersUpdateNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
