/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponent } from './authUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponent';
import type { AuthUsersResetPasswordConfirmCreateUidErrorComponent } from './authUsersResetPasswordConfirmCreateUidErrorComponent';
import type { AuthUsersResetPasswordConfirmCreateTokenErrorComponent } from './authUsersResetPasswordConfirmCreateTokenErrorComponent';
import type { AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponent } from './authUsersResetPasswordConfirmCreateNewPasswordErrorComponent';

export type AuthUsersResetPasswordConfirmCreateError = AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponent | AuthUsersResetPasswordConfirmCreateUidErrorComponent | AuthUsersResetPasswordConfirmCreateTokenErrorComponent | AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponent;
