/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMeUpdateError } from './authUsersMeUpdateError';
import type { AuthUsersMeUpdateValidationErrorType } from './authUsersMeUpdateValidationErrorType';

export interface AuthUsersMeUpdateValidationError {
  errors: AuthUsersMeUpdateError[];
  type: AuthUsersMeUpdateValidationErrorType;
}
