/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResendActivationCreateError } from './authUsersResendActivationCreateError';
import type { AuthUsersResendActivationCreateValidationErrorType } from './authUsersResendActivationCreateValidationErrorType';

export interface AuthUsersResendActivationCreateValidationError {
  errors: AuthUsersResendActivationCreateError[];
  type: AuthUsersResendActivationCreateValidationErrorType;
}
