/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMePartialUpdateNonFieldErrorsErrorComponent } from './authUsersMePartialUpdateNonFieldErrorsErrorComponent';
import type { AuthUsersMePartialUpdateEmailErrorComponent } from './authUsersMePartialUpdateEmailErrorComponent';

export type AuthUsersMePartialUpdateError = AuthUsersMePartialUpdateNonFieldErrorsErrorComponent | AuthUsersMePartialUpdateEmailErrorComponent;
