/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersCreateEmailErrorComponentAttr } from './authUsersCreateEmailErrorComponentAttr';
import type { AuthUsersCreateEmailErrorComponentCode } from './authUsersCreateEmailErrorComponentCode';

export interface AuthUsersCreateEmailErrorComponent {
  attr: AuthUsersCreateEmailErrorComponentAttr;
  /** * `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersCreateEmailErrorComponentCode;
  detail: string;
}
