/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersSetUsernameCreateError } from './authUsersSetUsernameCreateError';
import type { AuthUsersSetUsernameCreateValidationErrorType } from './authUsersSetUsernameCreateValidationErrorType';

export interface AuthUsersSetUsernameCreateValidationError {
  errors: AuthUsersSetUsernameCreateError[];
  type: AuthUsersSetUsernameCreateValidationErrorType;
}
