/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthDeviceTokenCreateError } from './authDeviceTokenCreateError';
import type { AuthDeviceTokenCreateValidationErrorType } from './authDeviceTokenCreateValidationErrorType';

export interface AuthDeviceTokenCreateValidationError {
  errors: AuthDeviceTokenCreateError[];
  type: AuthDeviceTokenCreateValidationErrorType;
}
