/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersActivationCreateNonFieldErrorsErrorComponent } from './authUsersActivationCreateNonFieldErrorsErrorComponent';
import type { AuthUsersActivationCreateUidErrorComponent } from './authUsersActivationCreateUidErrorComponent';
import type { AuthUsersActivationCreateTokenErrorComponent } from './authUsersActivationCreateTokenErrorComponent';

export type AuthUsersActivationCreateError = AuthUsersActivationCreateNonFieldErrorsErrorComponent | AuthUsersActivationCreateUidErrorComponent | AuthUsersActivationCreateTokenErrorComponent;
