/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordConfirmCreateValidationErrorType = typeof AuthUsersResetPasswordConfirmCreateValidationErrorType[keyof typeof AuthUsersResetPasswordConfirmCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordConfirmCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
