/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersSetUsernameCreateCurrentPasswordErrorComponentAttr = typeof AuthUsersSetUsernameCreateCurrentPasswordErrorComponentAttr[keyof typeof AuthUsersSetUsernameCreateCurrentPasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetUsernameCreateCurrentPasswordErrorComponentAttr = {
  current_password: 'current_password',
} as const;
