/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentAttr } from './authUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode } from './authUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode';

export interface AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponent {
  attr: AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `invalid_token` - invalid_token
* `invalid_uid` - invalid_uid */
  code: AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
