/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `inactive_account` - inactive_account
* `invalid` - invalid
* `invalid_credentials` - invalid_credentials
 */
export type AuthTokenLoginCreateNonFieldErrorsErrorComponentCode = typeof AuthTokenLoginCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthTokenLoginCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthTokenLoginCreateNonFieldErrorsErrorComponentCode = {
  inactive_account: 'inactive_account',
  invalid: 'invalid',
  invalid_credentials: 'invalid_credentials',
} as const;
