/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr } from './authUsersPartialUpdateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode } from './authUsersPartialUpdateNonFieldErrorsErrorComponentCode';

export interface AuthUsersPartialUpdateNonFieldErrorsErrorComponent {
  attr: AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
