/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResendActivationCreateEmailErrorComponentAttr = typeof AuthUsersResendActivationCreateEmailErrorComponentAttr[keyof typeof AuthUsersResendActivationCreateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResendActivationCreateEmailErrorComponentAttr = {
  email: 'email',
} as const;
