/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr = typeof AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr[keyof typeof AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersPartialUpdateNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
