/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponentAttr = typeof AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponentAttr[keyof typeof AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordConfirmCreateNewPasswordErrorComponentAttr = {
  new_password: 'new_password',
} as const;
