/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr } from './authUsersResetPasswordConfirmCreateUidErrorComponentAttr';
import type { AuthUsersResetPasswordConfirmCreateUidErrorComponentCode } from './authUsersResetPasswordConfirmCreateUidErrorComponentCode';

export interface AuthUsersResetPasswordConfirmCreateUidErrorComponent {
  attr: AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersResetPasswordConfirmCreateUidErrorComponentCode;
  detail: string;
}
