/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordCreateEmailErrorComponentAttr = typeof AuthUsersResetPasswordCreateEmailErrorComponentAttr[keyof typeof AuthUsersResetPasswordCreateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordCreateEmailErrorComponentAttr = {
  email: 'email',
} as const;
