/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenLoginCreateUsernameErrorComponentAttr } from './authTokenLoginCreateUsernameErrorComponentAttr';
import type { AuthTokenLoginCreateUsernameErrorComponentCode } from './authTokenLoginCreateUsernameErrorComponentCode';

export interface AuthTokenLoginCreateUsernameErrorComponent {
  attr: AuthTokenLoginCreateUsernameErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthTokenLoginCreateUsernameErrorComponentCode;
  detail: string;
}
