/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenLoginCreateError } from './authTokenLoginCreateError';
import type { AuthTokenLoginCreateValidationErrorType } from './authTokenLoginCreateValidationErrorType';

export interface AuthTokenLoginCreateValidationError {
  errors: AuthTokenLoginCreateError[];
  type: AuthTokenLoginCreateValidationErrorType;
}
