/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersActivationCreateError } from './authUsersActivationCreateError';
import type { AuthUsersActivationCreateValidationErrorType } from './authUsersActivationCreateValidationErrorType';

export interface AuthUsersActivationCreateValidationError {
  errors: AuthUsersActivationCreateError[];
  type: AuthUsersActivationCreateValidationErrorType;
}
