/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersCreateEmailErrorComponentAttr = typeof AuthUsersCreateEmailErrorComponentAttr[keyof typeof AuthUsersCreateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersCreateEmailErrorComponentAttr = {
  email: 'email',
} as const;
