/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthDeviceTokenCreateNonFieldErrorsErrorComponentAttr } from './authDeviceTokenCreateNonFieldErrorsErrorComponentAttr';
import type { AuthDeviceTokenCreateNonFieldErrorsErrorComponentCode } from './authDeviceTokenCreateNonFieldErrorsErrorComponentCode';

export interface AuthDeviceTokenCreateNonFieldErrorsErrorComponent {
  attr: AuthDeviceTokenCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: AuthDeviceTokenCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
