/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersSetPasswordCreateNonFieldErrorsErrorComponent } from './authUsersSetPasswordCreateNonFieldErrorsErrorComponent';
import type { AuthUsersSetPasswordCreateNewPasswordErrorComponent } from './authUsersSetPasswordCreateNewPasswordErrorComponent';
import type { AuthUsersSetPasswordCreateCurrentPasswordErrorComponent } from './authUsersSetPasswordCreateCurrentPasswordErrorComponent';

export type AuthUsersSetPasswordCreateError = AuthUsersSetPasswordCreateNonFieldErrorsErrorComponent | AuthUsersSetPasswordCreateNewPasswordErrorComponent | AuthUsersSetPasswordCreateCurrentPasswordErrorComponent;
