/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed
 */
export type AuthUsersResetPasswordCreateEmailErrorComponentCode = typeof AuthUsersResetPasswordCreateEmailErrorComponentCode[keyof typeof AuthUsersResetPasswordCreateEmailErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordCreateEmailErrorComponentCode = {
  blank: 'blank',
  invalid: 'invalid',
  null: 'null',
  null_characters_not_allowed: 'null_characters_not_allowed',
  required: 'required',
  surrogate_characters_not_allowed: 'surrogate_characters_not_allowed',
} as const;
