/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetUsernameCreateEmailErrorComponentAttr = typeof AuthUsersResetUsernameCreateEmailErrorComponentAttr[keyof typeof AuthUsersResetUsernameCreateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetUsernameCreateEmailErrorComponentAttr = {
  email: 'email',
} as const;
