/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr = typeof AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr[keyof typeof AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordConfirmCreateUidErrorComponentAttr = {
  uid: 'uid',
} as const;
