/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersCreatePasswordErrorComponentAttr = typeof AuthUsersCreatePasswordErrorComponentAttr[keyof typeof AuthUsersCreatePasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersCreatePasswordErrorComponentAttr = {
  password: 'password',
} as const;
