/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersSetPasswordCreateError } from './authUsersSetPasswordCreateError';
import type { AuthUsersSetPasswordCreateValidationErrorType } from './authUsersSetPasswordCreateValidationErrorType';

export interface AuthUsersSetPasswordCreateValidationError {
  errors: AuthUsersSetPasswordCreateError[];
  type: AuthUsersSetPasswordCreateValidationErrorType;
}
