/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersPartialUpdateError } from './authUsersPartialUpdateError';
import type { AuthUsersPartialUpdateValidationErrorType } from './authUsersPartialUpdateValidationErrorType';

export interface AuthUsersPartialUpdateValidationError {
  errors: AuthUsersPartialUpdateError[];
  type: AuthUsersPartialUpdateValidationErrorType;
}
