/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersMePartialUpdateEmailErrorComponentAttr = typeof AuthUsersMePartialUpdateEmailErrorComponentAttr[keyof typeof AuthUsersMePartialUpdateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersMePartialUpdateEmailErrorComponentAttr = {
  email: 'email',
} as const;
