/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameCreateEmailErrorComponentAttr } from './authUsersResetUsernameCreateEmailErrorComponentAttr';
import type { AuthUsersResetUsernameCreateEmailErrorComponentCode } from './authUsersResetUsernameCreateEmailErrorComponentCode';

export interface AuthUsersResetUsernameCreateEmailErrorComponent {
  attr: AuthUsersResetUsernameCreateEmailErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersResetUsernameCreateEmailErrorComponentCode;
  detail: string;
}
