/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponent } from './authUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponent';
import type { AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponent } from './authUsersResetUsernameConfirmCreateNewUsernameErrorComponent';

export type AuthUsersResetUsernameConfirmCreateError = AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponent | AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponent;
