/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
* `invalid_token` - invalid_token
* `invalid_uid` - invalid_uid
 */
export type AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetUsernameConfirmCreateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  invalid_token: 'invalid_token',
  invalid_uid: 'invalid_uid',
} as const;
