/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersUpdateNonFieldErrorsErrorComponent } from './authUsersUpdateNonFieldErrorsErrorComponent';
import type { AuthUsersUpdateEmailErrorComponent } from './authUsersUpdateEmailErrorComponent';

export type AuthUsersUpdateError = AuthUsersUpdateNonFieldErrorsErrorComponent | AuthUsersUpdateEmailErrorComponent;
