/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersActivationCreateUidErrorComponentAttr = typeof AuthUsersActivationCreateUidErrorComponentAttr[keyof typeof AuthUsersActivationCreateUidErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersActivationCreateUidErrorComponentAttr = {
  uid: 'uid',
} as const;
