/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameConfirmCreateError } from './authUsersResetUsernameConfirmCreateError';
import type { AuthUsersResetUsernameConfirmCreateValidationErrorType } from './authUsersResetUsernameConfirmCreateValidationErrorType';

export interface AuthUsersResetUsernameConfirmCreateValidationError {
  errors: AuthUsersResetUsernameConfirmCreateError[];
  type: AuthUsersResetUsernameConfirmCreateValidationErrorType;
}
