/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponentAttr = typeof AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponentAttr[keyof typeof AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetUsernameConfirmCreateNewUsernameErrorComponentAttr = {
  new_username: 'new_username',
} as const;
