/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResendActivationCreateNonFieldErrorsErrorComponent } from './authUsersResendActivationCreateNonFieldErrorsErrorComponent';
import type { AuthUsersResendActivationCreateEmailErrorComponent } from './authUsersResendActivationCreateEmailErrorComponent';

export type AuthUsersResendActivationCreateError = AuthUsersResendActivationCreateNonFieldErrorsErrorComponent | AuthUsersResendActivationCreateEmailErrorComponent;
