/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersSetUsernameCreateNonFieldErrorsErrorComponentAttr } from './authUsersSetUsernameCreateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersSetUsernameCreateNonFieldErrorsErrorComponentCode } from './authUsersSetUsernameCreateNonFieldErrorsErrorComponentCode';

export interface AuthUsersSetUsernameCreateNonFieldErrorsErrorComponent {
  attr: AuthUsersSetUsernameCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `invalid_password` - invalid_password */
  code: AuthUsersSetUsernameCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
