/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersSetPasswordCreateCurrentPasswordErrorComponentAttr = typeof AuthUsersSetPasswordCreateCurrentPasswordErrorComponentAttr[keyof typeof AuthUsersSetPasswordCreateCurrentPasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetPasswordCreateCurrentPasswordErrorComponentAttr = {
  current_password: 'current_password',
} as const;
