/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameCreateError } from './authUsersResetUsernameCreateError';
import type { AuthUsersResetUsernameCreateValidationErrorType } from './authUsersResetUsernameCreateValidationErrorType';

export interface AuthUsersResetUsernameCreateValidationError {
  errors: AuthUsersResetUsernameCreateError[];
  type: AuthUsersResetUsernameCreateValidationErrorType;
}
