/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetUsernameCreateValidationErrorType = typeof AuthUsersResetUsernameCreateValidationErrorType[keyof typeof AuthUsersResetUsernameCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetUsernameCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
