/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordCreateValidationErrorType = typeof AuthUsersResetPasswordCreateValidationErrorType[keyof typeof AuthUsersResetPasswordCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
