/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMeUpdateNonFieldErrorsErrorComponentAttr } from './authUsersMeUpdateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersMeUpdateNonFieldErrorsErrorComponentCode } from './authUsersMeUpdateNonFieldErrorsErrorComponentCode';

export interface AuthUsersMeUpdateNonFieldErrorsErrorComponent {
  attr: AuthUsersMeUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: AuthUsersMeUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
