/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersPartialUpdateEmailErrorComponentAttr = typeof AuthUsersPartialUpdateEmailErrorComponentAttr[keyof typeof AuthUsersPartialUpdateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersPartialUpdateEmailErrorComponentAttr = {
  email: 'email',
} as const;
