/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetPasswordConfirmCreateError } from './authUsersResetPasswordConfirmCreateError';
import type { AuthUsersResetPasswordConfirmCreateValidationErrorType } from './authUsersResetPasswordConfirmCreateValidationErrorType';

export interface AuthUsersResetPasswordConfirmCreateValidationError {
  errors: AuthUsersResetPasswordConfirmCreateError[];
  type: AuthUsersResetPasswordConfirmCreateValidationErrorType;
}
