/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersUpdateEmailErrorComponentAttr = typeof AuthUsersUpdateEmailErrorComponentAttr[keyof typeof AuthUsersUpdateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersUpdateEmailErrorComponentAttr = {
  email: 'email',
} as const;
