/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersCreateNonFieldErrorsErrorComponent } from './authUsersCreateNonFieldErrorsErrorComponent';
import type { AuthUsersCreateEmailErrorComponent } from './authUsersCreateEmailErrorComponent';
import type { AuthUsersCreateUsernameErrorComponent } from './authUsersCreateUsernameErrorComponent';
import type { AuthUsersCreatePasswordErrorComponent } from './authUsersCreatePasswordErrorComponent';

export type AuthUsersCreateError = AuthUsersCreateNonFieldErrorsErrorComponent | AuthUsersCreateEmailErrorComponent | AuthUsersCreateUsernameErrorComponent | AuthUsersCreatePasswordErrorComponent;
