/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersUpdateError } from './authUsersUpdateError';
import type { AuthUsersUpdateValidationErrorType } from './authUsersUpdateValidationErrorType';

export interface AuthUsersUpdateValidationError {
  errors: AuthUsersUpdateError[];
  type: AuthUsersUpdateValidationErrorType;
}
