/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersMeUpdateEmailErrorComponentAttr = typeof AuthUsersMeUpdateEmailErrorComponentAttr[keyof typeof AuthUsersMeUpdateEmailErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersMeUpdateEmailErrorComponentAttr = {
  email: 'email',
} as const;
