/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentAttr } from './authUsersSetPasswordCreateNonFieldErrorsErrorComponentAttr';
import type { AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode } from './authUsersSetPasswordCreateNonFieldErrorsErrorComponentCode';

export interface AuthUsersSetPasswordCreateNonFieldErrorsErrorComponent {
  attr: AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `invalid_password` - invalid_password */
  code: AuthUsersSetPasswordCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
