/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMePartialUpdateEmailErrorComponentAttr } from './authUsersMePartialUpdateEmailErrorComponentAttr';
import type { AuthUsersMePartialUpdateEmailErrorComponentCode } from './authUsersMePartialUpdateEmailErrorComponentCode';

export interface AuthUsersMePartialUpdateEmailErrorComponent {
  attr: AuthUsersMePartialUpdateEmailErrorComponentAttr;
  /** * `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersMePartialUpdateEmailErrorComponentCode;
  detail: string;
}
