/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenLoginCreateNonFieldErrorsErrorComponentAttr } from './authTokenLoginCreateNonFieldErrorsErrorComponentAttr';
import type { AuthTokenLoginCreateNonFieldErrorsErrorComponentCode } from './authTokenLoginCreateNonFieldErrorsErrorComponentCode';

export interface AuthTokenLoginCreateNonFieldErrorsErrorComponent {
  attr: AuthTokenLoginCreateNonFieldErrorsErrorComponentAttr;
  /** * `inactive_account` - inactive_account
* `invalid` - invalid
* `invalid_credentials` - invalid_credentials */
  code: AuthTokenLoginCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
