/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersResetPasswordConfirmCreateTokenErrorComponentAttr = typeof AuthUsersResetPasswordConfirmCreateTokenErrorComponentAttr[keyof typeof AuthUsersResetPasswordConfirmCreateTokenErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordConfirmCreateTokenErrorComponentAttr = {
  token: 'token',
} as const;
