/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersSetPasswordCreateNewPasswordErrorComponentAttr = typeof AuthUsersSetPasswordCreateNewPasswordErrorComponentAttr[keyof typeof AuthUsersSetPasswordCreateNewPasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetPasswordCreateNewPasswordErrorComponentAttr = {
  new_password: 'new_password',
} as const;
