/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersSetUsernameCreateValidationErrorType = typeof AuthUsersSetUsernameCreateValidationErrorType[keyof typeof AuthUsersSetUsernameCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetUsernameCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
