/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthTokenLoginCreatePasswordErrorComponentAttr = typeof AuthTokenLoginCreatePasswordErrorComponentAttr[keyof typeof AuthTokenLoginCreatePasswordErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthTokenLoginCreatePasswordErrorComponentAttr = {
  password: 'password',
} as const;
