/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersUpdateValidationErrorType = typeof AuthUsersUpdateValidationErrorType[keyof typeof AuthUsersUpdateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersUpdateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
