/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersActivationCreateTokenErrorComponentAttr = typeof AuthUsersActivationCreateTokenErrorComponentAttr[keyof typeof AuthUsersActivationCreateTokenErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersActivationCreateTokenErrorComponentAttr = {
  token: 'token',
} as const;
