/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
 */
export type AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode = typeof AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersPartialUpdateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
} as const;
