/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersCreateUsernameErrorComponentAttr = typeof AuthUsersCreateUsernameErrorComponentAttr[keyof typeof AuthUsersCreateUsernameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersCreateUsernameErrorComponentAttr = {
  username: 'username',
} as const;
