/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
* `invalid_token` - invalid_token
* `invalid_uid` - invalid_uid
* `stale_token` - stale_token
 */
export type AuthUsersActivationCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersActivationCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersActivationCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersActivationCreateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  invalid_token: 'invalid_token',
  invalid_uid: 'invalid_uid',
  stale_token: 'stale_token',
} as const;
