/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersResetUsernameCreateNonFieldErrorsErrorComponent } from './authUsersResetUsernameCreateNonFieldErrorsErrorComponent';
import type { AuthUsersResetUsernameCreateEmailErrorComponent } from './authUsersResetUsernameCreateEmailErrorComponent';

export type AuthUsersResetUsernameCreateError = AuthUsersResetUsernameCreateNonFieldErrorsErrorComponent | AuthUsersResetUsernameCreateEmailErrorComponent;
