/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `cannot_create_user` - cannot_create_user
* `invalid` - invalid
 */
export type AuthUsersCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersCreateNonFieldErrorsErrorComponentCode = {
  cannot_create_user: 'cannot_create_user',
  invalid: 'invalid',
} as const;
