/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthDeviceTokenCreateNonFieldErrorsErrorComponent } from './authDeviceTokenCreateNonFieldErrorsErrorComponent';
import type { AuthDeviceTokenCreateCodeErrorComponent } from './authDeviceTokenCreateCodeErrorComponent';

export type AuthDeviceTokenCreateError = AuthDeviceTokenCreateNonFieldErrorsErrorComponent | AuthDeviceTokenCreateCodeErrorComponent;
