/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersPartialUpdateEmailErrorComponentAttr } from './authUsersPartialUpdateEmailErrorComponentAttr';
import type { AuthUsersPartialUpdateEmailErrorComponentCode } from './authUsersPartialUpdateEmailErrorComponentCode';

export interface AuthUsersPartialUpdateEmailErrorComponent {
  attr: AuthUsersPartialUpdateEmailErrorComponentAttr;
  /** * `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: AuthUsersPartialUpdateEmailErrorComponentCode;
  detail: string;
}
