/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthUsersMeUpdateNonFieldErrorsErrorComponent } from './authUsersMeUpdateNonFieldErrorsErrorComponent';
import type { AuthUsersMeUpdateEmailErrorComponent } from './authUsersMeUpdateEmailErrorComponent';

export type AuthUsersMeUpdateError = AuthUsersMeUpdateNonFieldErrorsErrorComponent | AuthUsersMeUpdateEmailErrorComponent;
