/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
* `invalid_token` - invalid_token
* `invalid_uid` - invalid_uid
 */
export type AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode = typeof AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode[keyof typeof AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersResetPasswordConfirmCreateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  invalid_token: 'invalid_token',
  invalid_uid: 'invalid_uid',
} as const;
