/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type AuthUsersSetUsernameCreateNewUsernameErrorComponentAttr = typeof AuthUsersSetUsernameCreateNewUsernameErrorComponentAttr[keyof typeof AuthUsersSetUsernameCreateNewUsernameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthUsersSetUsernameCreateNewUsernameErrorComponentAttr = {
  new_username: 'new_username',
} as const;
