/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ClientErrorEnum = typeof ClientErrorEnum[keyof typeof ClientErrorEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientErrorEnum = {
  client_error: 'client_error',
} as const;
