/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentCreateDescriptionErrorComponentAttr = typeof ControlEquipmentCreateDescriptionErrorComponentAttr[keyof typeof ControlEquipmentCreateDescriptionErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentCreateDescriptionErrorComponentAttr = {
  description: 'description',
} as const;
