/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentUpdateNonFieldErrorsErrorComponent } from './controlEquipmentUpdateNonFieldErrorsErrorComponent';
import type { ControlEquipmentUpdateNameErrorComponent } from './controlEquipmentUpdateNameErrorComponent';
import type { ControlEquipmentUpdateDescriptionErrorComponent } from './controlEquipmentUpdateDescriptionErrorComponent';

export type ControlEquipmentUpdateError = ControlEquipmentUpdateNonFieldErrorsErrorComponent | ControlEquipmentUpdateNameErrorComponent | ControlEquipmentUpdateDescriptionErrorComponent;
