/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlDevicesPartialUpdateNameErrorComponentAttr = typeof ControlDevicesPartialUpdateNameErrorComponentAttr[keyof typeof ControlDevicesPartialUpdateNameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesPartialUpdateNameErrorComponentAttr = {
  name: 'name',
} as const;
