/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentPartialUpdateError } from './controlEquipmentPartialUpdateError';
import type { ControlEquipmentPartialUpdateValidationErrorType } from './controlEquipmentPartialUpdateValidationErrorType';

export interface ControlEquipmentPartialUpdateValidationError {
  errors: ControlEquipmentPartialUpdateError[];
  type: ControlEquipmentPartialUpdateValidationErrorType;
}
