/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentUpdateNonFieldErrorsErrorComponentAttr } from './controlEquipmentUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlEquipmentUpdateNonFieldErrorsErrorComponentCode } from './controlEquipmentUpdateNonFieldErrorsErrorComponentCode';

export interface ControlEquipmentUpdateNonFieldErrorsErrorComponent {
  attr: ControlEquipmentUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlEquipmentUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
