/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsUpdateIndicatorTypeErrorComponentAttr = typeof ControlIndicatorsUpdateIndicatorTypeErrorComponentAttr[keyof typeof ControlIndicatorsUpdateIndicatorTypeErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsUpdateIndicatorTypeErrorComponentAttr = {
  indicator_type: 'indicator_type',
} as const;
