/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentUpdateDescriptionErrorComponentAttr = typeof ControlEquipmentUpdateDescriptionErrorComponentAttr[keyof typeof ControlEquipmentUpdateDescriptionErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentUpdateDescriptionErrorComponentAttr = {
  description: 'description',
} as const;
