/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr } from './controlIndicatorsUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode } from './controlIndicatorsUpdateNonFieldErrorsErrorComponentCode';

export interface ControlIndicatorsUpdateNonFieldErrorsErrorComponent {
  attr: ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
