/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesUpdateError } from './controlDevicesUpdateError';
import type { ControlDevicesUpdateValidationErrorType } from './controlDevicesUpdateValidationErrorType';

export interface ControlDevicesUpdateValidationError {
  errors: ControlDevicesUpdateError[];
  type: ControlDevicesUpdateValidationErrorType;
}
