/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr = typeof ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr[keyof typeof ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsUpdateNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
