/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `date` - date
* `invalid` - invalid
* `make_aware` - make_aware
* `overflow` - overflow
 */
export type ControlDevicesUpdateLastActiveErrorComponentCode = typeof ControlDevicesUpdateLastActiveErrorComponentCode[keyof typeof ControlDevicesUpdateLastActiveErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesUpdateLastActiveErrorComponentCode = {
  date: 'date',
  invalid: 'invalid',
  make_aware: 'make_aware',
  overflow: 'overflow',
} as const;
