/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentCreateNonFieldErrorsErrorComponent } from './controlEquipmentCreateNonFieldErrorsErrorComponent';
import type { ControlEquipmentCreateNameErrorComponent } from './controlEquipmentCreateNameErrorComponent';
import type { ControlEquipmentCreateDescriptionErrorComponent } from './controlEquipmentCreateDescriptionErrorComponent';

export type ControlEquipmentCreateError = ControlEquipmentCreateNonFieldErrorsErrorComponent | ControlEquipmentCreateNameErrorComponent | ControlEquipmentCreateDescriptionErrorComponent;
