/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsUpdateEquipmentErrorComponentAttr = typeof ControlIndicatorsUpdateEquipmentErrorComponentAttr[keyof typeof ControlIndicatorsUpdateEquipmentErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsUpdateEquipmentErrorComponentAttr = {
  equipment: 'equipment',
} as const;
