/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentPartialUpdateNameErrorComponentAttr = typeof ControlEquipmentPartialUpdateNameErrorComponentAttr[keyof typeof ControlEquipmentPartialUpdateNameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentPartialUpdateNameErrorComponentAttr = {
  name: 'name',
} as const;
