/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentPartialUpdateDescriptionErrorComponentAttr = typeof ControlEquipmentPartialUpdateDescriptionErrorComponentAttr[keyof typeof ControlEquipmentPartialUpdateDescriptionErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentPartialUpdateDescriptionErrorComponentAttr = {
  description: 'description',
} as const;
