/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentCreateNonFieldErrorsErrorComponentAttr } from './controlEquipmentCreateNonFieldErrorsErrorComponentAttr';
import type { ControlEquipmentCreateNonFieldErrorsErrorComponentCode } from './controlEquipmentCreateNonFieldErrorsErrorComponentCode';

export interface ControlEquipmentCreateNonFieldErrorsErrorComponent {
  attr: ControlEquipmentCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlEquipmentCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
