/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsCreateMaxValueErrorComponentAttr = typeof ControlIndicatorsCreateMaxValueErrorComponentAttr[keyof typeof ControlIndicatorsCreateMaxValueErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsCreateMaxValueErrorComponentAttr = {
  max_value: 'max_value',
} as const;
