/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentAttr } from './controlIndicatorsPartialUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode } from './controlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode';

export interface ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponent {
  attr: ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
