/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsPartialUpdateIndicatorTypeErrorComponentAttr = typeof ControlIndicatorsPartialUpdateIndicatorTypeErrorComponentAttr[keyof typeof ControlIndicatorsPartialUpdateIndicatorTypeErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsPartialUpdateIndicatorTypeErrorComponentAttr = {
  indicator_type: 'indicator_type',
} as const;
