/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsUpdateError } from './controlIndicatorsUpdateError';
import type { ControlIndicatorsUpdateValidationErrorType } from './controlIndicatorsUpdateValidationErrorType';

export interface ControlIndicatorsUpdateValidationError {
  errors: ControlIndicatorsUpdateError[];
  type: ControlIndicatorsUpdateValidationErrorType;
}
