/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
 */
export type ControlEquipmentUpdateNonFieldErrorsErrorComponentCode = typeof ControlEquipmentUpdateNonFieldErrorsErrorComponentCode[keyof typeof ControlEquipmentUpdateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentUpdateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
} as const;
