/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
 */
export type ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode = typeof ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode[keyof typeof ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsUpdateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
} as const;
