/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentUpdateValidationErrorType = typeof ControlEquipmentUpdateValidationErrorType[keyof typeof ControlEquipmentUpdateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentUpdateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
