/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `date` - date
* `invalid` - invalid
* `make_aware` - make_aware
* `overflow` - overflow
 */
export type ControlDevicesPartialUpdateLastActiveErrorComponentCode = typeof ControlDevicesPartialUpdateLastActiveErrorComponentCode[keyof typeof ControlDevicesPartialUpdateLastActiveErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesPartialUpdateLastActiveErrorComponentCode = {
  date: 'date',
  invalid: 'invalid',
  make_aware: 'make_aware',
  overflow: 'overflow',
} as const;
