/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentCreateValidationErrorType = typeof ControlEquipmentCreateValidationErrorType[keyof typeof ControlEquipmentCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
