/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesPartialUpdateLastActiveErrorComponentAttr } from './controlDevicesPartialUpdateLastActiveErrorComponentAttr';
import type { ControlDevicesPartialUpdateLastActiveErrorComponentCode } from './controlDevicesPartialUpdateLastActiveErrorComponentCode';

export interface ControlDevicesPartialUpdateLastActiveErrorComponent {
  attr: ControlDevicesPartialUpdateLastActiveErrorComponentAttr;
  /** * `date` - date
* `invalid` - invalid
* `make_aware` - make_aware
* `overflow` - overflow */
  code: ControlDevicesPartialUpdateLastActiveErrorComponentCode;
  detail: string;
}
