/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlEquipmentUpdateNameErrorComponentAttr = typeof ControlEquipmentUpdateNameErrorComponentAttr[keyof typeof ControlEquipmentUpdateNameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlEquipmentUpdateNameErrorComponentAttr = {
  name: 'name',
} as const;
