/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsPartialUpdateEquipmentErrorComponentAttr } from './controlIndicatorsPartialUpdateEquipmentErrorComponentAttr';
import type { ControlIndicatorsPartialUpdateEquipmentErrorComponentCode } from './controlIndicatorsPartialUpdateEquipmentErrorComponentCode';

export interface ControlIndicatorsPartialUpdateEquipmentErrorComponent {
  attr: ControlIndicatorsPartialUpdateEquipmentErrorComponentAttr;
  /** * `does_not_exist` - does_not_exist
* `incorrect_type` - incorrect_type */
  code: ControlIndicatorsPartialUpdateEquipmentErrorComponentCode;
  detail: string;
}
