/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsCreateMinValueErrorComponentAttr = typeof ControlIndicatorsCreateMinValueErrorComponentAttr[keyof typeof ControlIndicatorsCreateMinValueErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsCreateMinValueErrorComponentAttr = {
  min_value: 'min_value',
} as const;
