/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
 */
export type ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode = typeof ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode[keyof typeof ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
} as const;
