/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `does_not_exist` - does_not_exist
* `incorrect_type` - incorrect_type
 */
export type ControlIndicatorsCreateEquipmentErrorComponentCode = typeof ControlIndicatorsCreateEquipmentErrorComponentCode[keyof typeof ControlIndicatorsCreateEquipmentErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsCreateEquipmentErrorComponentCode = {
  does_not_exist: 'does_not_exist',
  incorrect_type: 'incorrect_type',
} as const;
