/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlDevicesPartialUpdateLastActiveErrorComponentAttr = typeof ControlDevicesPartialUpdateLastActiveErrorComponentAttr[keyof typeof ControlDevicesPartialUpdateLastActiveErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesPartialUpdateLastActiveErrorComponentAttr = {
  last_active: 'last_active',
} as const;
