/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentCreateError } from './controlEquipmentCreateError';
import type { ControlEquipmentCreateValidationErrorType } from './controlEquipmentCreateValidationErrorType';

export interface ControlEquipmentCreateValidationError {
  errors: ControlEquipmentCreateError[];
  type: ControlEquipmentCreateValidationErrorType;
}
