/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsCreateEquipmentErrorComponentAttr = typeof ControlIndicatorsCreateEquipmentErrorComponentAttr[keyof typeof ControlIndicatorsCreateEquipmentErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsCreateEquipmentErrorComponentAttr = {
  equipment: 'equipment',
} as const;
