/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentPartialUpdateNonFieldErrorsErrorComponentAttr } from './controlEquipmentPartialUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlEquipmentPartialUpdateNonFieldErrorsErrorComponentCode } from './controlEquipmentPartialUpdateNonFieldErrorsErrorComponentCode';

export interface ControlEquipmentPartialUpdateNonFieldErrorsErrorComponent {
  attr: ControlEquipmentPartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlEquipmentPartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
