/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsCreateNonFieldErrorsErrorComponentAttr } from './controlIndicatorsCreateNonFieldErrorsErrorComponentAttr';
import type { ControlIndicatorsCreateNonFieldErrorsErrorComponentCode } from './controlIndicatorsCreateNonFieldErrorsErrorComponentCode';

export interface ControlIndicatorsCreateNonFieldErrorsErrorComponent {
  attr: ControlIndicatorsCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlIndicatorsCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
