/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentPartialUpdateNonFieldErrorsErrorComponent } from './controlEquipmentPartialUpdateNonFieldErrorsErrorComponent';
import type { ControlEquipmentPartialUpdateNameErrorComponent } from './controlEquipmentPartialUpdateNameErrorComponent';
import type { ControlEquipmentPartialUpdateDescriptionErrorComponent } from './controlEquipmentPartialUpdateDescriptionErrorComponent';

export type ControlEquipmentPartialUpdateError = ControlEquipmentPartialUpdateNonFieldErrorsErrorComponent | ControlEquipmentPartialUpdateNameErrorComponent | ControlEquipmentPartialUpdateDescriptionErrorComponent;
