/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsCreateNonFieldErrorsErrorComponent } from './controlIndicatorsCreateNonFieldErrorsErrorComponent';
import type { ControlIndicatorsCreateEquipmentErrorComponent } from './controlIndicatorsCreateEquipmentErrorComponent';
import type { ControlIndicatorsCreateIndicatorTypeErrorComponent } from './controlIndicatorsCreateIndicatorTypeErrorComponent';
import type { ControlIndicatorsCreateMinValueErrorComponent } from './controlIndicatorsCreateMinValueErrorComponent';
import type { ControlIndicatorsCreateMaxValueErrorComponent } from './controlIndicatorsCreateMaxValueErrorComponent';

export type ControlIndicatorsCreateError = ControlIndicatorsCreateNonFieldErrorsErrorComponent | ControlIndicatorsCreateEquipmentErrorComponent | ControlIndicatorsCreateIndicatorTypeErrorComponent | ControlIndicatorsCreateMinValueErrorComponent | ControlIndicatorsCreateMaxValueErrorComponent;
