/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesPartialUpdateNonFieldErrorsErrorComponent } from './controlDevicesPartialUpdateNonFieldErrorsErrorComponent';
import type { ControlDevicesPartialUpdateNameErrorComponent } from './controlDevicesPartialUpdateNameErrorComponent';
import type { ControlDevicesPartialUpdateLastActiveErrorComponent } from './controlDevicesPartialUpdateLastActiveErrorComponent';

export type ControlDevicesPartialUpdateError = ControlDevicesPartialUpdateNonFieldErrorsErrorComponent | ControlDevicesPartialUpdateNameErrorComponent | ControlDevicesPartialUpdateLastActiveErrorComponent;
