/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlIndicatorsPartialUpdateMinValueErrorComponentAttr = typeof ControlIndicatorsPartialUpdateMinValueErrorComponentAttr[keyof typeof ControlIndicatorsPartialUpdateMinValueErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsPartialUpdateMinValueErrorComponentAttr = {
  min_value: 'min_value',
} as const;
