/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr } from './controlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlDevicesPartialUpdateNonFieldErrorsErrorComponentCode } from './controlDevicesPartialUpdateNonFieldErrorsErrorComponentCode';

export interface ControlDevicesPartialUpdateNonFieldErrorsErrorComponent {
  attr: ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlDevicesPartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
