/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesPartialUpdateValidationError } from './controlDevicesPartialUpdateValidationError';
import type { ParseErrorResponse } from './parseErrorResponse';

export type ControlDevicesPartialUpdateErrorResponse400 = ControlDevicesPartialUpdateValidationError | ParseErrorResponse;
