/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `blank` - blank
* `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed
 */
export type ControlIndicatorsPartialUpdateMaxValueErrorComponentCode = typeof ControlIndicatorsPartialUpdateMaxValueErrorComponentCode[keyof typeof ControlIndicatorsPartialUpdateMaxValueErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlIndicatorsPartialUpdateMaxValueErrorComponentCode = {
  blank: 'blank',
  invalid: 'invalid',
  max_length: 'max_length',
  null: 'null',
  null_characters_not_allowed: 'null_characters_not_allowed',
  required: 'required',
  surrogate_characters_not_allowed: 'surrogate_characters_not_allowed',
} as const;
