/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ParseErrorResponse } from './parseErrorResponse';

export type ControlIndicatorsValuesRetrieveErrorResponse400 = ParseErrorResponse;
