/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponent } from './controlIndicatorsPartialUpdateNonFieldErrorsErrorComponent';
import type { ControlIndicatorsPartialUpdateEquipmentErrorComponent } from './controlIndicatorsPartialUpdateEquipmentErrorComponent';
import type { ControlIndicatorsPartialUpdateIndicatorTypeErrorComponent } from './controlIndicatorsPartialUpdateIndicatorTypeErrorComponent';
import type { ControlIndicatorsPartialUpdateMinValueErrorComponent } from './controlIndicatorsPartialUpdateMinValueErrorComponent';
import type { ControlIndicatorsPartialUpdateMaxValueErrorComponent } from './controlIndicatorsPartialUpdateMaxValueErrorComponent';

export type ControlIndicatorsPartialUpdateError = ControlIndicatorsPartialUpdateNonFieldErrorsErrorComponent | ControlIndicatorsPartialUpdateEquipmentErrorComponent | ControlIndicatorsPartialUpdateIndicatorTypeErrorComponent | ControlIndicatorsPartialUpdateMinValueErrorComponent | ControlIndicatorsPartialUpdateMaxValueErrorComponent;
