/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsUpdateNonFieldErrorsErrorComponent } from './controlIndicatorsUpdateNonFieldErrorsErrorComponent';
import type { ControlIndicatorsUpdateEquipmentErrorComponent } from './controlIndicatorsUpdateEquipmentErrorComponent';
import type { ControlIndicatorsUpdateIndicatorTypeErrorComponent } from './controlIndicatorsUpdateIndicatorTypeErrorComponent';
import type { ControlIndicatorsUpdateMinValueErrorComponent } from './controlIndicatorsUpdateMinValueErrorComponent';
import type { ControlIndicatorsUpdateMaxValueErrorComponent } from './controlIndicatorsUpdateMaxValueErrorComponent';

export type ControlIndicatorsUpdateError = ControlIndicatorsUpdateNonFieldErrorsErrorComponent | ControlIndicatorsUpdateEquipmentErrorComponent | ControlIndicatorsUpdateIndicatorTypeErrorComponent | ControlIndicatorsUpdateMinValueErrorComponent | ControlIndicatorsUpdateMaxValueErrorComponent;
