/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlDevicesUpdateLastActiveErrorComponentAttr = typeof ControlDevicesUpdateLastActiveErrorComponentAttr[keyof typeof ControlDevicesUpdateLastActiveErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesUpdateLastActiveErrorComponentAttr = {
  last_active: 'last_active',
} as const;
