/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlEquipmentUpdateError } from './controlEquipmentUpdateError';
import type { ControlEquipmentUpdateValidationErrorType } from './controlEquipmentUpdateValidationErrorType';

export interface ControlEquipmentUpdateValidationError {
  errors: ControlEquipmentUpdateError[];
  type: ControlEquipmentUpdateValidationErrorType;
}
