/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsPartialUpdateError } from './controlIndicatorsPartialUpdateError';
import type { ControlIndicatorsPartialUpdateValidationErrorType } from './controlIndicatorsPartialUpdateValidationErrorType';

export interface ControlIndicatorsPartialUpdateValidationError {
  errors: ControlIndicatorsPartialUpdateError[];
  type: ControlIndicatorsPartialUpdateValidationErrorType;
}
