/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesUpdateLastActiveErrorComponentAttr } from './controlDevicesUpdateLastActiveErrorComponentAttr';
import type { ControlDevicesUpdateLastActiveErrorComponentCode } from './controlDevicesUpdateLastActiveErrorComponentCode';

export interface ControlDevicesUpdateLastActiveErrorComponent {
  attr: ControlDevicesUpdateLastActiveErrorComponentAttr;
  /** * `date` - date
* `invalid` - invalid
* `make_aware` - make_aware
* `overflow` - overflow */
  code: ControlDevicesUpdateLastActiveErrorComponentCode;
  detail: string;
}
