/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesUpdateNonFieldErrorsErrorComponentAttr } from './controlDevicesUpdateNonFieldErrorsErrorComponentAttr';
import type { ControlDevicesUpdateNonFieldErrorsErrorComponentCode } from './controlDevicesUpdateNonFieldErrorsErrorComponentCode';

export interface ControlDevicesUpdateNonFieldErrorsErrorComponent {
  attr: ControlDevicesUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: ControlDevicesUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
