/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlDevicesUpdateNonFieldErrorsErrorComponent } from './controlDevicesUpdateNonFieldErrorsErrorComponent';
import type { ControlDevicesUpdateNameErrorComponent } from './controlDevicesUpdateNameErrorComponent';
import type { ControlDevicesUpdateLastActiveErrorComponent } from './controlDevicesUpdateLastActiveErrorComponent';

export type ControlDevicesUpdateError = ControlDevicesUpdateNonFieldErrorsErrorComponent | ControlDevicesUpdateNameErrorComponent | ControlDevicesUpdateLastActiveErrorComponent;
