/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsCreateEquipmentErrorComponentAttr } from './controlIndicatorsCreateEquipmentErrorComponentAttr';
import type { ControlIndicatorsCreateEquipmentErrorComponentCode } from './controlIndicatorsCreateEquipmentErrorComponentCode';

export interface ControlIndicatorsCreateEquipmentErrorComponent {
  attr: ControlIndicatorsCreateEquipmentErrorComponentAttr;
  /** * `does_not_exist` - does_not_exist
* `incorrect_type` - incorrect_type */
  code: ControlIndicatorsCreateEquipmentErrorComponentCode;
  detail: string;
}
