/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ControlIndicatorsCreateError } from './controlIndicatorsCreateError';
import type { ControlIndicatorsCreateValidationErrorType } from './controlIndicatorsCreateValidationErrorType';

export interface ControlIndicatorsCreateValidationError {
  errors: ControlIndicatorsCreateError[];
  type: ControlIndicatorsCreateValidationErrorType;
}
