/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr = typeof ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr[keyof typeof ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlDevicesPartialUpdateNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
