/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateIndicatorIdErrorComponentAttr } from './dataSavePhotoCreateIndicatorIdErrorComponentAttr';
import type { DataSavePhotoCreateIndicatorIdErrorComponentCode } from './dataSavePhotoCreateIndicatorIdErrorComponentCode';

export interface DataSavePhotoCreateIndicatorIdErrorComponent {
  attr: DataSavePhotoCreateIndicatorIdErrorComponentAttr;
  /** * `invalid` - invalid
* `max_string_length` - max_string_length
* `null` - null
* `required` - required */
  code: DataSavePhotoCreateIndicatorIdErrorComponentCode;
  detail: string;
}
