/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type DataSavePhotoCreateEquipmentIdErrorComponentAttr = typeof DataSavePhotoCreateEquipmentIdErrorComponentAttr[keyof typeof DataSavePhotoCreateEquipmentIdErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateEquipmentIdErrorComponentAttr = {
  equipment_id: 'equipment_id',
} as const;
