/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateEquipmentIdErrorComponentAttr } from './dataSavePhotoCreateEquipmentIdErrorComponentAttr';
import type { DataSavePhotoCreateEquipmentIdErrorComponentCode } from './dataSavePhotoCreateEquipmentIdErrorComponentCode';

export interface DataSavePhotoCreateEquipmentIdErrorComponent {
  attr: DataSavePhotoCreateEquipmentIdErrorComponentAttr;
  /** * `invalid` - invalid
* `max_string_length` - max_string_length
* `null` - null
* `required` - required */
  code: DataSavePhotoCreateEquipmentIdErrorComponentCode;
  detail: string;
}
