/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateNonFieldErrorsErrorComponentAttr } from './dataSavePhotoCreateNonFieldErrorsErrorComponentAttr';
import type { DataSavePhotoCreateNonFieldErrorsErrorComponentCode } from './dataSavePhotoCreateNonFieldErrorsErrorComponentCode';

export interface DataSavePhotoCreateNonFieldErrorsErrorComponent {
  attr: DataSavePhotoCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid */
  code: DataSavePhotoCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
