/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type DataSavePhotoCreateIndicatorIdErrorComponentAttr = typeof DataSavePhotoCreateIndicatorIdErrorComponentAttr[keyof typeof DataSavePhotoCreateIndicatorIdErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateIndicatorIdErrorComponentAttr = {
  indicator_id: 'indicator_id',
} as const;
