/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateNonFieldErrorsErrorComponent } from './dataSavePhotoCreateNonFieldErrorsErrorComponent';
import type { DataSavePhotoCreateIndicatorIdErrorComponent } from './dataSavePhotoCreateIndicatorIdErrorComponent';
import type { DataSavePhotoCreateImageErrorComponent } from './dataSavePhotoCreateImageErrorComponent';
import type { DataSavePhotoCreateFilenameErrorComponent } from './dataSavePhotoCreateFilenameErrorComponent';

export type DataSavePhotoCreateError = DataSavePhotoCreateNonFieldErrorsErrorComponent | DataSavePhotoCreateIndicatorIdErrorComponent | DataSavePhotoCreateImageErrorComponent | DataSavePhotoCreateFilenameErrorComponent;
