/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type DataSavePhotoCreateImageErrorComponentAttr = typeof DataSavePhotoCreateImageErrorComponentAttr[keyof typeof DataSavePhotoCreateImageErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateImageErrorComponentAttr = {
  image: 'image',
} as const;
