/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateImageErrorComponentAttr } from './dataSavePhotoCreateImageErrorComponentAttr';
import type { DataSavePhotoCreateImageErrorComponentCode } from './dataSavePhotoCreateImageErrorComponentCode';

export interface DataSavePhotoCreateImageErrorComponent {
  attr: DataSavePhotoCreateImageErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: DataSavePhotoCreateImageErrorComponentCode;
  detail: string;
}
