/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type DataSavePhotoCreateFilenameErrorComponentAttr = typeof DataSavePhotoCreateFilenameErrorComponentAttr[keyof typeof DataSavePhotoCreateFilenameErrorComponentAttr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateFilenameErrorComponentAttr = {
  filename: 'filename',
} as const;
