/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { DataSavePhotoCreateNonFieldErrorsErrorComponent } from './dataSavePhotoCreateNonFieldErrorsErrorComponent';
import type { DataSavePhotoCreateEquipmentIdErrorComponent } from './dataSavePhotoCreateEquipmentIdErrorComponent';
import type { DataSavePhotoCreateImageErrorComponent } from './dataSavePhotoCreateImageErrorComponent';
import type { DataSavePhotoCreateFilenameErrorComponent } from './dataSavePhotoCreateFilenameErrorComponent';

export type DataSavePhotoCreateError = DataSavePhotoCreateNonFieldErrorsErrorComponent | DataSavePhotoCreateEquipmentIdErrorComponent | DataSavePhotoCreateImageErrorComponent | DataSavePhotoCreateFilenameErrorComponent;
