/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type DataSavePhotoCreateValidationErrorType = typeof DataSavePhotoCreateValidationErrorType[keyof typeof DataSavePhotoCreateValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
