/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invalid` - invalid
* `max_string_length` - max_string_length
* `null` - null
* `required` - required
 */
export type DataSavePhotoCreateIndicatorIdErrorComponentCode = typeof DataSavePhotoCreateIndicatorIdErrorComponentCode[keyof typeof DataSavePhotoCreateIndicatorIdErrorComponentCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSavePhotoCreateIndicatorIdErrorComponentCode = {
  invalid: 'invalid',
  max_string_length: 'max_string_length',
  null: 'null',
  required: 'required',
} as const;
