/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export interface Equipment {
  description: string;
  readonly id: number;
  name?: string;
}
