/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode403Enum } from './errorCode403Enum';

export interface Error403 {
  attr: string | null;
  /** * `permission_denied` - Permission Denied */
  code: ErrorCode403Enum;
  detail: string;
}
