/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode406Enum = typeof ErrorCode406Enum[keyof typeof ErrorCode406Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode406Enum = {
  not_acceptable: 'not_acceptable',
} as const;
