/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { Error401 } from './error401';
import type { ClientErrorEnum } from './clientErrorEnum';

export interface ErrorResponse401 {
  errors: Error401[];
  /** * `client_error` - Client Error */
  type: ClientErrorEnum;
}
