/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { Error405 } from './error405';
import type { ClientErrorEnum } from './clientErrorEnum';

export interface ErrorResponse405 {
  errors: Error405[];
  /** * `client_error` - Client Error */
  type: ClientErrorEnum;
}
