/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode500Enum } from './errorCode500Enum';

export interface Error500 {
  attr: string | null;
  /** * `error` - Error */
  code: ErrorCode500Enum;
  detail: string;
}
