/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { Error500 } from './error500';
import type { ServerErrorEnum } from './serverErrorEnum';

export interface ErrorResponse500 {
  errors: Error500[];
  /** * `server_error` - Server Error */
  type: ServerErrorEnum;
}
