/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode415Enum } from './errorCode415Enum';

export interface Error415 {
  attr: string | null;
  /** * `unsupported_media_type` - Unsupported Media Type */
  code: ErrorCode415Enum;
  detail: string;
}
