/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode415Enum = typeof ErrorCode415Enum[keyof typeof ErrorCode415Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode415Enum = {
  unsupported_media_type: 'unsupported_media_type',
} as const;
