/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode401Enum = typeof ErrorCode401Enum[keyof typeof ErrorCode401Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode401Enum = {
  authentication_failed: 'authentication_failed',
  not_authenticated: 'not_authenticated',
} as const;
