/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode500Enum = typeof ErrorCode500Enum[keyof typeof ErrorCode500Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode500Enum = {
  error: 'error',
} as const;
