/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode405Enum = typeof ErrorCode405Enum[keyof typeof ErrorCode405Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode405Enum = {
  method_not_allowed: 'method_not_allowed',
} as const;
