/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode404Enum = typeof ErrorCode404Enum[keyof typeof ErrorCode404Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode404Enum = {
  not_found: 'not_found',
} as const;
