/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode405Enum } from './errorCode405Enum';

export interface Error405 {
  attr: string | null;
  /** * `method_not_allowed` - Method Not Allowed */
  code: ErrorCode405Enum;
  detail: string;
}
