/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { Error404 } from './error404';
import type { ClientErrorEnum } from './clientErrorEnum';

export interface ErrorResponse404 {
  errors: Error404[];
  /** * `client_error` - Client Error */
  type: ClientErrorEnum;
}
