/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode404Enum } from './errorCode404Enum';

export interface Error404 {
  attr: string | null;
  /** * `not_found` - Not Found */
  code: ErrorCode404Enum;
  detail: string;
}
