/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode403Enum = typeof ErrorCode403Enum[keyof typeof ErrorCode403Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode403Enum = {
  permission_denied: 'permission_denied',
} as const;
