/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export interface Indicators {
  equipment?: number | null;
  readonly id: number;
  indicator_type?: string;
  max_value: string;
  min_value: string;
}
