/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ParseErrorCodeEnum = typeof ParseErrorCodeEnum[keyof typeof ParseErrorCodeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParseErrorCodeEnum = {
  parse_error: 'parse_error',
} as const;
