/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordResetConfirm {
  new_password: string;
  token: string;
  uid: string;
}
