/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export type ServerErrorEnum = typeof ServerErrorEnum[keyof typeof ServerErrorEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerErrorEnum = {
  server_error: 'server_error',
} as const;
