/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Sensorium API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  email?: string;
  readonly id: number;
  /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
  readonly username: string;
}
